/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.lazyskulptor.hrsaclient;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest(properties = "spring.config.location=classpath:/application.yml")
@ExtendWith(ContainerExtension.class)
class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
    }
}
